# Generated by Django 2.2.28 on 2024-10-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20241020_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
