# Generated by Django 2.2.28 on 2024-10-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20241021_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
