# Generated by Django 2.2.28 on 2024-09-22 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240922_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 16, 43, 1, 72353, tzinfo=utc)),
        ),
    ]
