# Generated by Django 2.2.28 on 2024-09-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='categor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categore',
            field=models.ManyToManyField(to='blog.categor'),
        ),
    ]
